sensing/lidar/top/ouster/os_sensor:
# ouster/os_sensor:
  ros__parameters:
    sensor_hostname: '192.168.4.119'
    udp_dest: ''
    mtp_dest: ''
    mtp_main: false
    lidar_mode: ''
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    udp_profile_lidar: ''
    metadata: ''
    lidar_port: 0
    imu_port: 0
    use_system_default_qos: False
sensing/lidar/top/ouster/os_cloud:
# ouster/os_cloud:
  ros__parameters:
    sensor_frame: 'ouster_top_base_link'
    lidar_frame: 'os_lidar_top'
    imu_frame: 'os_imu_top'
    timestamp_mode: 'TIME_FROM_ROS_TIME'
    proc_mask: IMU|PCL|SCAN # pick IMU, PCL, SCAN or any combination of the three options
    use_system_default_qos: False # needs to match the value defined for os_sensor node
    scan_ring: 0  # Use this parameter in conjunction with the SCAN flag and choose a
                  # value the range [0, sensor_beams_count)
sensing/lidar/top/ouster/os_image:
# ouster/os_image:
    use_system_default_qos: False # needs to match the value defined for os_sensor node
